### ISSUE TITLE
Parameter used to query authors not right 

### ISSUE THREAD

**Issue by mguidoti** [plazi/BLR-website#19]
Hi Teodor,

We noticed that you guys are using a not existing parameter to query authors in both `Images` and `Publications` data types.

Please, instead of authorityName use **`author`** for [Images](https://zenodeo.punkish.org/docs#/v2/getV2Images) and **`creator`** for [Publications](https://zenodeo.punkish.org/docs#/v2/getV2Publications), according to [Zenodeo documentation](https://zenodeo.punkish.org/docs#/v2/).

**Comment by punkish** [comment]
this might have been a result of rejigging the queries between versions, or it could have been an error on my part. But please note, the relevant parameter now is "creator" for both images and publications, as this is what Zenodo calls this role. The creator is usually the author.

This is certainly one of the params that should enable inexact searches. I am in the process of testing that.

**Comment by punkish** [comment]
hello everyone, esp @mguidoti @teodorgeorgiev (but also @tcatapano and @myrmoteras), I have pushed new changes for fetching images and publications by `creator` and `title`. The ElasticSearch syntax is pretty non-standard so I've tried to make things as intuitive as possible. Please check the docs on zenodeo.

**Impt:** Please note that when you search by `title` or by `creator`, the `q` field (ostensibly the fulltext field) is used internally to construct the query, and as such, it is ignored as far as the user is concerned. Here is an illustrative example

`.../publications?q=foobar&creator=Agosti&title=Effects` will actually ignore **foobar** and use `q` to search for the prescribed `creator` and `title`. I will confirm the mechanics of this with @slint but as far as I understand, since `creator` and `title` are used by `q` to construct the query, they take precedence over any other free-ranging search.

I am closing this issue for now. If you experience problems, please open a new issue with the specific problem. Many thanks.
