### ISSUE TITLE
Set up project call

### ISSUE THREAD

**Issue by tcatapano** [plazi/BLR-website#23]
@punkish @teodorgeorgiev @mguidoti @myrmoteras: 

I'd like to schedule a call to review status and discuss a roadmap for development of the BLR website. Perhaps Monday?

**Comment by mguidoti** [comment]
Monday is fine by me.

**Comment by myrmoteras** [comment]
@tcatapano Monday, what time? For me any time is ok. Shall we say 4:30pm CET?

**Comment by punkish** [comment]
yea, 4:30-5:30 PM CET will work for me

**Comment by teodorgeorgiev** [comment]
Monday between 4:30-5:30 PM CET is OK for me

**Comment by tcatapano** [comment]
OK. Sending out a calendar invite for 4:30-5:30 CET. Can we use Hangouts/Meet. It is helpful that is connected to the calendar?

**Comment by punkish** [comment]
> Can we use Hangouts/Meet

Yes please, let's try that. I have another reason for it. With Hangouts, as far as I remember, I can turn off all incoming video. I am kinda sequestered in my apt because of the "state of alarm" in Spain because of Covid, and at home I have limited bandwidth (using my phone data). I was hoping to go to my makerspace for this call, but now I can't. So, I have to work as efficiently as possible. Skype doesn't allow turning off incoming video, but with Hangouts, those who want video can use it and those who don't can turn it off.

**Comment by tcatapano** [comment]
Ive sent an invite. Here too is a link:

https://calendar.google.com/calendar/r/eventedit/MWYzNGU0NGlhbGVwZzcwdGwwaGhrdHVyajcgMDZzdGtoZHNyZzUzYTljMDBpcWNpNjJhM2dAZw?tab=mc1&pli=1
