### ISSUE TITLE
BLR testing: what to test?

### ISSUE THREAD

**Issue by myrmoteras** [plazi/BLR-website#26]
@teodorgeorgiev can you please let me and @mguidoti know, what functionality we should check?

**Comment by teodorgeorgiev** [comment]
@myrmoteras @mguidoti 
Please test the search and filter functionality here: http://blr.uplaysandbox.website/

We have hidden for now the search options "Community" & "Institution/Collection" because the current version of the API does not support any of them.

Please note that if you select to search by "Taxon" or "Journal" the "Images" & "Publication" data types are disabled because the current version of the API does not support them.

cc @punkish

**Comment by myrmoteras** [comment]
I do the same checks as before, and nothing seems to have changed?!  #25, #26

**Comment by teodorgeorgiev** [comment]
When you open the website please click "ctrl + shift + R" to refresh the page.

Then you can search for treatments by Author, but please note the search is case sensitive:

![image](https://user-images.githubusercontent.com/4538487/77079880-51511000-6a01-11ea-934a-9b7ee1c82c49.png)

**Comment by punkish** [comment]
case-sensitive searches will be changed in the next update (not)
